server:
  port: 8080

management:
  context-path: /admin

spring:
  application:
    name: cellnet
  datasource:
    url: jdbc:oracle:thin:@esppdtd1scan.vzbi.com:1800/CMFEBDEV
    username: postgres
    password: dcgmplc
#    driver-class-name: oracle.jdbc.OracleDriver